 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/doctor_shifts", type: :request do
  # DoctorShift. As you add validations to DoctorShift, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DoctorShift.create! valid_attributes
      get doctor_shifts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      doctor_shift = DoctorShift.create! valid_attributes
      get doctor_shift_url(doctor_shift)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_doctor_shift_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      doctor_shift = DoctorShift.create! valid_attributes
      get edit_doctor_shift_url(doctor_shift)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DoctorShift" do
        expect {
          post doctor_shifts_url, params: { doctor_shift: valid_attributes }
        }.to change(DoctorShift, :count).by(1)
      end

      it "redirects to the created doctor_shift" do
        post doctor_shifts_url, params: { doctor_shift: valid_attributes }
        expect(response).to redirect_to(doctor_shift_url(DoctorShift.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DoctorShift" do
        expect {
          post doctor_shifts_url, params: { doctor_shift: invalid_attributes }
        }.to change(DoctorShift, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post doctor_shifts_url, params: { doctor_shift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested doctor_shift" do
        doctor_shift = DoctorShift.create! valid_attributes
        patch doctor_shift_url(doctor_shift), params: { doctor_shift: new_attributes }
        doctor_shift.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the doctor_shift" do
        doctor_shift = DoctorShift.create! valid_attributes
        patch doctor_shift_url(doctor_shift), params: { doctor_shift: new_attributes }
        doctor_shift.reload
        expect(response).to redirect_to(doctor_shift_url(doctor_shift))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        doctor_shift = DoctorShift.create! valid_attributes
        patch doctor_shift_url(doctor_shift), params: { doctor_shift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested doctor_shift" do
      doctor_shift = DoctorShift.create! valid_attributes
      expect {
        delete doctor_shift_url(doctor_shift)
      }.to change(DoctorShift, :count).by(-1)
    end

    it "redirects to the doctor_shifts list" do
      doctor_shift = DoctorShift.create! valid_attributes
      delete doctor_shift_url(doctor_shift)
      expect(response).to redirect_to(doctor_shifts_url)
    end
  end
end
